Repository eosnetworkfoundation/grant-framework, pull requests merged in 2022-06, with the labels that each got.

#20 TrustSwap decentralized exchange / TrustEVM ✨
  applications/trustswap.md
Labels: Grant Received, Grant Committee Approved, Grant Fully Approved, Grant Translated

#16 CETF
  applications/CETF.md
Labels: Grant Received, Grant Committee Approved, Grant Fully Approved, Grant Translated

#23 Chronicle grant application
  applications/chronicle.md
Labels: Grant Received, Grant Committee Approved, Grant Translated

#25 Revert "Chronicle grant application"
  applications/chronicle.md
Labels: Grant Received, Grant Committee Approved

#26 chronicle - re-submitted
  applications/chronicle.md
Labels: Grant Received, Grant Committee Approved, Grant Fully Approved, Grant Translated
